/**
 * @storybook/test-runner configuration.
 *
 * Boots the static Storybook server, opens every story in a real browser, and
 * runs:
 *   1. An explicit axe-core accessibility audit via `checkA11y` from
 *      axe-playwright, which reads the global `a11y.test` parameter set in
 *      `.storybook/preview.tsx`:
 *        - `'todo'` (default in CI): violations are logged but tests pass.
 *        - `'error'` (when STORYBOOK_A11Y_ENFORCE=true): violations fail.
 *   2. Any `play()` functions on the story (catches broken interactions that
 *      would otherwise silently regress).
 *
 * The test-runner is invoked from CI (see `.github/workflows/ci.yml` →
 * `storybook-test-runner` job) after `build-storybook` produces the static
 * bundle and the job starts a local HTTP server serving `storybook-static/`
 * on port 6006. The runner connects to that live server and discovers stories
 * via the index JSON generated by `storybook build`.
 *
 * Phased rollout
 * --------------
 * The existing Storybook stories had not been audited for a11y when this
 * runner was introduced; this PR turns the check on at `'todo'` so we can
 * see the violations in CI logs. A follow-up PR will ratchet the default
 * to `'error'` after the existing violations are remediated. See issue #77.
 *
 * Reference: https://storybook.js.org/docs/writing-tests/test-runner
 */
import type { TestRunnerConfig } from '@storybook/test-runner';
import { getStoryContext } from '@storybook/test-runner';
import { checkA11y, injectAxe } from 'axe-playwright';

const config: TestRunnerConfig = {
  async postVisit(page, context) {
    const storyContext = await getStoryContext(page, context);
    const a11yConfig = storyContext.parameters?.a11y;

    // Skip entirely when a11y is disabled for this story
    if (a11yConfig?.disable) return;

    await injectAxe(page);

    const shouldFail = a11yConfig?.test === 'error';

    await checkA11y(
      page,
      '#storybook-root',
      {
        detailedReport: true,
        axeOptions: a11yConfig?.options,
      },
      !shouldFail,
    );
  },
};

export default config;
